BookReadingEvent/Controllers/RegistrationController.cs
using DataAccess.Models;
using Services.IRepository;
using Services.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookReadingEvent.Controllers
{
    /// <summary>
    /// Perform Registration for users
    /// </summary>
    [AllowAnonymous]
    public class RegistrationController : Controller
    {
        private DatabaseContext databaseContext = new DatabaseContext();
        IRegistration Iregistration;
        IRole Irole;
        /// <summary>
        /// 
        /// </summary>
        /// <param name="registration"></param>
        /// <param name="role"></param>
        public RegistrationController(IRegistration registration, IRole role)
        {
            Iregistration = registration;
            Irole = role;


        }
        /// <summary>
        /// 
        /// </summary>
        public RegistrationController()
        {
            Iregistration = new RegistrationRepo();
            Irole = new RoleRepo();
        }
       /// <summary>
       /// Get the list of all the users
       /// </summary>
       /// <returns></returns>
        public ActionResult Index()
        {
            List<Registration> @registration = databaseContext.Registrations.ToList();

            
            return View(registration);
           
        }

        /// <summary>
        /// get the registration form
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// post the form data into database for registration
        /// </summary>
        /// <param name="registration"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        
         public ActionResult Create(Registration registration)
        {
            var isEmailExist = Iregistration.CheckEmailExists(registration.Email);
            if(isEmailExist)
            {
                ModelState.AddModelError("", errorMessage: "Email Already used!! Try Unique One");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    Iregistration.AddUser(registration);

                    int userid = databaseContext.Registrations.Max(x => x.UserId);
                    Irole.AddRole(userid);

                    return RedirectToAction("Index", "Home");
                    
                }
            }
            
            return View();

        }

        /// <summary>
        /// Get from for editing user information
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit()
        {
            int id =int.Parse( User.Identity.Name);
            Registration @registration = databaseContext.Registrations.Single(userid => userid.UserId ==id );
            return View(registration);

        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit_Post()
        {
            try
            {
                int id = int.Parse(User.Identity.Name);
                Registration @registration = databaseContext.Registrations.Single(userid => userid.UserId == id);
                UpdateModel(@registration, new string[] { "UserId", "Name", "Email", "Password"});
                Iregistration.UpdateUser(@registration);

                return RedirectToAction("Home","Event");
            }
            catch
            {
                return View();
            }
        }

        
    }
}

BookReadingEvent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Book Reading Event", "Home", "Event", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Event")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>


                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Create Event", "Create", "Event")</li>
                        <li>@Html.ActionLink("View Event", "Index", "Event")</li>

                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Edit Event", "AdminEdit", "Event")</li>
                            <li>@Html.ActionLink("Users", "Index", "Registration")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Edit Event", "EditIndex", "Event")</li>
                            <li>@Html.ActionLink("My Event", "MyEvent", "Event")</li>
                            <li>@Html.ActionLink("Event Invited", "EventInvite", "Event")</li>
                            <li>@Html.ActionLink("Update Profile", "Edit", "Registration")</li>

                        }

                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BookReading Event</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>